### ISSUE TITLE
Missing tagged releases on DockerHub since 2.3.6

### ISSUE THREAD

**Issue by jokay** [sensepost/gowitness#168]
**Describe the bug**

There were some missing tagged releases on DockerHub since **2.3.6**.

Missing tags are **2.4.0**, **2.4.1**, **2.4.2**.

**To Reproduce**

1. Go to [DockerHub](https://hub.docker.com/r/leonjza/gowitness/tags?page=1)
2. Look at the **tags**

**Expected behavior**

Would be great to have all releases (tags) from GitHub on DockerHub available as well.

**Screenshots**

![image](https://user-images.githubusercontent.com/18613935/207035973-df712de5-fd50-499a-acbb-a90ead433745.png)

**Comment by jokay** [comment]
May be this helps for a multi-arch build supporting semantic versioning?

```yml
build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Get Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/leonjza/gowitness
          docker.io/leonjza/gowitness
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
```
